name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  just_audio: ^0.9.34
  device_info_plus: ^9.0.2
  path_provider: ^2.0.15
  audio_video_progress_bar: ^1.0.1  # Añade esta línea

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
